### ISSUE TITLE
Redirecting back to our site after successful transaction

### ISSUE THREAD

**Issue by nepaakash** [TheBikramLama/hbl#7]
I am getting "Page Expired " error while redirecting back to my site. How do I Solve?

**Comment by TheBikramLama** [comment]
Hi, this issue is not related to the package however, here's the solution to your query.
Since HBL sends a POST request to your backend_url after the user completes an action in HBL's portal, but Laravel requires a CSRF token to be available in all POST requests, Laravel responds with a code 419 (Page expired).
All you need to do is whitelist the backend_url in Laravel's VerifyCsrfToken middleware.
Here's how:
1. Open this file: `app\Http\Middleware\VerifyCsrfToken.php`
2. Add your backend_url to `$except` array.

Eg: If your backen_url is `https://yoursite.com/hbl/payment-process` then the `$except` parameter should look like this:
```php
protected $except = [
	"hbl/payment-process"
];
```

Hope this solves the issue. I'll make sure to include this instruction when I next update the documentations for the package.

**Comment by nepaakash** [comment]
Thank You ! Solved it.

**Comment by rajtech101** [comment]
@TheBikramLama , can you please update the documentation?

Thanks.
